In [1]:
import pandas as pd

In [2]:
air_quality_df = pd.read_csv("../data/airquality.csv")
air_quality_df.head()

   id       pm10      pm2_5     us_aqi   us_pm2_5    us_pm10    us_no2
0   1  24.705069  15.832259  74.846085  62.892975  22.433071  4.978726
1   2  24.705069  15.832259  74.846085  62.892975  22.433071  4.978726
2   3  36.463833  19.930069  79.891680  70.672390  31.697279  9.088648
3   4  54.698410  20.782001  78.130990  72.362310  44.380844  3.544936
4   5  54.698410  20.782001  78.130990  72.362310  44.380844  3.544936

In [3]:
green_covarage_df = pd.read_csv("../data/greenCovarage.csv")
green_covarage_df.head()

   id     lat     lon  green_coverage_pct
0   1  30.222  31.732                1.79
1   2  30.238  31.700                0.10
2   3  29.853  31.387                1.05
3   4  29.985  30.963                4.21
4   5  29.941  30.908                0.30

In [4]:
green_covarage_df = green_covarage_df[['id', 'green_coverage_pct']]
green_covarage_df.head()

   id  green_coverage_pct
0   1                1.79
1   2                0.10
2   3                1.05
3   4                4.21
4   5                0.30

In [5]:
merged_df = pd.merge(left=air_quality_df, right=green_covarage_df, on='id', how="left")
merged_df.head()

,id,pm10,pm2_5,us_aqi,us_pm2_5,us_pm10,us_no2,green_coverage_pct
0,1,24.705069,15.832259,74.846085,62.892975,22.433071,4.978726,1.79
1,2,24.705069,15.832259,74.846085,62.892975,22.433071,4.978726,0.10
2,3,36.463833,19.930069,79.891680,70.672390,31.697279,9.088648,1.05
3,4,54.698410,20.782001,78.130990,72.362310,44.380844,3.544936,4.21
4,5,54.698410,20.782001,78.130990,72.362310,44.380844,3.544936,0.30

In [7]:
districts_df = pd.read_csv("../data/districts.csv")
districts_df.head()

,id,name_en,name_ar,slug,lat,lon,parent_id,gov_en,gov_ar
0,EG1309,10 Ramadan 1,قسم اول مدينة العاشر من رمضان,10-ramadan-1-eg1309,30.222,31.732,EG13,Sharkia,الشرقية
1,EG1321,10 Ramadan 2,قسم ثان مدينه العاشر من رمضان,10-ramadan-2-eg1321,30.238,31.700,EG13,Sharkia,الشرقية
2,EG0103,15 Mayu,قسم 15 مايو,15-mayu-eg0103,29.853,31.387,EG01,Cairo,القاهرة
3,EG2107,6 October-1,قسم أول 6 أكتوبر,6-october-1-eg2107,29.985,30.963,EG21,Giza,الجيزة
4,EG2121,6 October-2,قسم ثان 6 أكتوبر,6-october-2-eg2121,29.941,30.908,EG21,Giza,الجيزة

In [8]:
locations_df = pd.read_csv("../data/locations.csv")
locations_df.head()

   id     lat     lon
0   1  30.222  31.732
1   2  30.238  31.700
2   3  29.853  31.387
3   4  29.985  30.963
4   5  29.941  30.908

In [9]:
merged_df = pd.merge(left=merged_df, right=locations_df, how="left", on="id")
merged_df.head()

,id,pm10,pm2_5,us_aqi,us_pm2_5,us_pm10,us_no2,green_coverage_pct,lat,lon
0,1,24.705069,15.832259,74.846085,62.892975,22.433071,4.978726,1.79,30.222,31.732
1,2,24.705069,15.832259,74.846085,62.892975,22.433071,4.978726,0.10,30.238,31.700
2,3,36.463833,19.930069,79.891680,70.672390,31.697279,9.088648,1.05,29.853,31.387
3,4,54.698410,20.782001,78.130990,72.362310,44.380844,3.544936,4.21,29.985,30.963
4,5,54.698410,20.782001,78.130990,72.362310,44.380844,3.544936,0.30,29.941,30.908

In [10]:
merged_df = pd.merge(left=merged_df, right=districts_df, how="left", on="lat")

In [11]:
merged_df.head()

,id_x,pm10,pm2_5,us_aqi,us_pm2_5,us_pm10,us_no2,green_coverage_pct,lat,lon_x,id_y,name_en,name_ar,slug,lon_y,parent_id,gov_en,gov_ar
0,1,24.705069,15.832259,74.846085,62.892975,22.433071,4.978726,1.79,30.222,31.732,EG1309,10 Ramadan 1,قسم اول مدينة العاشر من رمضان,10-ramadan-1-eg1309,31.732,EG13,Sharkia,الشرقية
1,2,24.705069,15.832259,74.846085,62.892975,22.433071,4.978726,0.10,30.238,31.700,EG1321,10 Ramadan 2,قسم ثان مدينه العاشر من رمضان,10-ramadan-2-eg1321,31.700,EG13,Sharkia,الشرقية
2,3,36.463833,19.930069,79.891680,70.672390,31.697279,9.088648,1.05,29.853,31.387,EG0103,15 Mayu,قسم 15 مايو,15-mayu-eg0103,31.387,EG01,Cairo,القاهرة
3,4,54.698410,20.782001,78.130990,72.362310,44.380844,3.544936,4.21,29.985,30.963,EG2107,6 October-1,قسم أول 6 أكتوبر,6-october-1-eg2107,30.963,EG21,Giza,الجيزة
4,5,54.698410,20.782001,78.130990,72.362310,44.380844,3.544936,0.30,29.941,30.908,EG2121,6 October-2,قسم ثان 6 أكتوبر,6-october-2-eg2121,30.908,EG21,Giza,الجيزة

In [12]:
final_df = merged_df[['name_en', 'name_ar', 'pm10', 'pm2_5', 'us_aqi', 'us_pm2_5', 'us_pm10', 'us_no2', 'green_coverage_pct', 'gov_en', 'gov_ar']]

In [13]:
final_df.head()

,name_en,name_ar,pm10,pm2_5,us_aqi,us_pm2_5,us_pm10,us_no2,green_coverage_pct,gov_en,gov_ar
0,10 Ramadan 1,قسم اول مدينة العاشر من رمضان,24.705069,15.832259,74.846085,62.892975,22.433071,4.978726,1.79,Sharkia,الشرقية
1,10 Ramadan 2,قسم ثان مدينه العاشر من رمضان,24.705069,15.832259,74.846085,62.892975,22.433071,4.978726,0.10,Sharkia,الشرقية
2,15 Mayu,قسم 15 مايو,36.463833,19.930069,79.891680,70.672390,31.697279,9.088648,1.05,Cairo,القاهرة
3,6 October-1,قسم أول 6 أكتوبر,54.698410,20.782001,78.130990,72.362310,44.380844,3.544936,4.21,Giza,الجيزة
4,6 October-2,قسم ثان 6 أكتوبر,54.698410,20.782001,78.130990,72.362310,44.380844,3.544936,0.30,Giza,الجيزة

In [14]:
final_df.to_csv('../data/qol.csv', sep=",", index=False, header=True)